server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: shakib19
    url: jdbc:mysql://localhost:3306/springApp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show:
      show-sql: 'true                  '
welcome:
  message: Welcome to backend development world